apiVersion: v1
kind: ConfigMap
metadata:
  name: gxf-initcontainer-config
data:
  remove-old-test-files.sh: |
    #!/bin/sh
    OUTPUT_PATH=/target/output
    JOB_NAME=$1
    echo "Current files in ${OUTPUT_PATH}"
    ls $OUTPUT_PATH
    rm -rf $OUTPUT_PATH/$JOB_NAME
    echo "Current files after removal in ${OUTPUT_PATH}"
    ls $OUTPUT_PATH
---
{{- range $job := .Values.jobs -}}
{{- $name := $job.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
data:
  global-cucumber.properties: |
    # Postgres
    db.hostname=postgres

    # OSLP
q    oslp.security.signkey.path=/etc/ssl/certs/oslp/oslp_sim_ecdsa_private.der
    oslp.security.verifykey.path=/etc/ssl/certs/oslp/oslp_test_ecdsa_public.der

    # Cucumber
    certificate.basepath=/etc/ssl/certs/organizations/
    web.service.truststore.location=/etc/ssl/certs/organizations/trust.jks
    web.service.keystore.password=${ORGANISATION_KEYSTORE_PASSWORD}
    web.service.truststore.password=${ORGANISATION_TRUSTSTORE_PASSWORD}
    web.service.core.notification.address={{ $name }}
    web.service.publiclighting.notification.address={{ $name }}
    web.service.smartmetering.notification.address={{ $name }}

    server=httpd
    domain=:443
    platform=osgp-protocol-adapter-oslpqq

    response.url.notification.address={{ $name }}
    device.networkaddress={{ $name }}
---
{{- end }}
