{{- range $job := .Values.jobs -}}
{{- $name := $job.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
    {{- range $port := $job.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
    {{- end }}
  selector:
    app: {{ $name }}
  # Headless service for direct Job pod access
  clusterIP: None
---
{{- end -}}
