apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  ports:
    - name: console
      port: 8161
      targetPort: console
    - name: activemq
      port: 61617
      targetPort: activemq
  selector:
    app: activemq
