apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-config
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"
    ServerName httpd

    PidFile /tmp/httpd.pid

    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
    LoadModule ssl_module modules/mod_ssl.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so
    LoadModule rewrite_module modules/mod_rewrite.so

    User daemon
    Group daemon

    ErrorLog /proc/self/fd/2
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    RequestHeader unset Proxy early
    TypesConfig conf/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz

    SSLPassPhraseDialog |/certs/server-key-password

    SSLSessionCache         shmcb:/var/cache/mod_ssl/scache(512000)
    SSLSessionCacheTimeout  300

    Mutex default

    SSLRandomSeed startup file:/dev/urandom  256
    SSLRandomSeed connect builtin
    SSLCryptoDevice builtin

    Include /usr/local/apache2/conf/vhosts.conf
  vhosts.conf: |
    Listen 80
    <VirtualHost *:80>

      ProxyPass /probe https://httpd/probe
      ProxyPass /proxy-server https://httpd/proxy-server

      ProxyPass /osgp-adapter-ws-smartmetering https://osgp-adapter-ws-smartmetering/osgp-adapter-ws-smartmetering
      ProxyPass /osgp-adapter-ws-publiclighting https://osgp-adapter-ws-publiclighting/osgp-adapter-ws-publiclighting
      ProxyPass /osgp-adapter-ws-tariffswitching https://osgp-adapter-ws-tariffswitching/osgp-adapter-ws-tariffswitching
      ProxyPass /osgp-adapter-ws-admin https://osgp-adapter-ws-admin/osgp-adapter-ws-admin
      ProxyPass /osgp-adapter-ws-core https://osgp-adapter-ws-core/osgp-adapter-ws-core
      ProxyPass /osgp-web-device-simulator https://osgp-web-device-simulator/osgp-web-device-simulator
      ProxyPass /sm-integration https://sm-integration/sm-integration

      <Location /server-status>
        SetHandler server-status
      </Location>

    </VirtualHost>

    <IfModule ssl_module>
      Listen 9443
      <VirtualHost *:9443>
        ErrorLog /dev/stderr
        LogLevel info
        CustomLog /dev/stdout combined

        SSLEngine on
        SSLProtocol -all +TLSv1.2 -TLSv1.3

        SSLCertificateFile /certs/server.crt
        SSLCertificateKeyFile /certs/server.key
        SSLCACertificateFile /certs/root.crt

        BrowserMatch "MSIE [2-6]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [7-9]" ssl-unclean-shutdown

        <IfModule mod_proxy_ajp.c>
            #
            # To use the proxy-server, configure web-applications as follows. Original web-application URL:
            # https://my-host:443/osgp-adapter-ws-core/common/deviceManagementService/
            # Proxy-server web-application URL:
            # https://my-host:443/proxy-server/osgp-adapter-ws-core/common/deviceManagementService/
            #
            ProxyPass /proxy-server ajp://httpd:8009/proxy-server
            ProxyPassReverse /proxy-server /proxy-server

            ProxyPass /osgp-adapter-ws-publiclighting ajp://osgp-adapter-ws-publiclighting:8009/osgp-adapter-ws-publiclighting
            ProxyPassReverse /osgp-adapter-ws-publiclighting /osgp-adapter-ws-publiclighting

            ProxyPass /osgp-adapter-ws-tariffswitching ajp://osgp-adapter-ws-tariffswitching:8009/osgp-adapter-ws-tariffswitching
            ProxyPassReverse /osgp-adapter-ws-tariffswitching /osgp-adapter-ws-tariffswitching

            ProxyPass /osgp-adapter-ws-smartmetering ajp://osgp-adapter-ws-smartmetering:8009/osgp-adapter-ws-smartmetering
            ProxyPassReverse /osgp-adapter-ws-smartmetering /osgp-adapter-ws-smartmetering

            ProxyPass /osgp-adapter-ws-admin ajp://osgp-adapter-ws-admin:8009/osgp-adapter-ws-admin
            ProxyPassReverse /osgp-adapter-ws-admin /osgp-adapter-ws-admin

            ProxyPass /osgp-adapter-ws-core ajp://osgp-adapter-ws-core:8009
            ProxyPassReverse /osgp-adapter-ws-core /osgp-adapter-ws-core

            ProxyPass /web-device-simulator ajp://web-device-simulator:8009/web-device-simulator
            ProxyPassReverse /web-device-simulator /web-device-simulator

            ProxyPass /probe ajp://httpd:8009/probe
            ProxyPassReverse /probe /probe

            ProxyPass /sm-integration ajp://localhost:8009/sm-integration
            ProxyPassReverse /sm-integration /sm-integration
        </IfModule>

        # Proxy Server SSL settings.
        <Location /proxy-server>
            SSLVerifyClient require
            SSLVerifyDepth 1

            SSLOptions +ExportCertData

            # This property is set to 10 mb as max for transferring files
            SSLRenegBufferSize 10486000
        </Location>

        <Location /osgp-adapter-ws-admin>
          SSLVerifyClient require
          SSLVerifyDepth 1
          SSLOptions +ExportCertData
        </Location>

        <Location /osgp-adapter-ws-admin/wsdl>
          SSLVerifyClient none
        </Location>

        <Location /osgp-adapter-ws-core>
          SSLVerifyClient require
          SSLVerifyDepth 1
          SSLOptions +ExportCertData
          SSLRenegBufferSize 5243000
        </Location>

        <Location /osgp-adapter-ws-core/wsdl>
          SSLVerifyClient none
        </Location>

        <Location /osgp-adapter-ws-publiclighting>
          SSLVerifyClient require
          SSLVerifyDepth 1
          SSLOptions +ExportCertData
        </Location>

        <Location /osgp-adapter-ws-publiclighting/wsdl>
          SSLVerifyClient none
        </Location>

        <Location /osgp-adapter-ws-tariffswitching>
          SSLVerifyClient require
          SSLVerifyDepth 1
          SSLOptions +ExportCertData
        </Location>

        <Location /osgp-adapter-ws-tariffswitching/wsdl>
          SSLVerifyClient none
        </Location>

        # Smart Meter Web Service Adapter SSL settings.
        <Location /osgp-adapter-ws-smartmetering>
            SSLVerifyClient require
            SSLVerifyDepth 1

            SSLOptions +ExportCertData
        </Location>
        <Location /osgp-adapter-ws-smartmetering/wsdl>
            SSLVerifyClient none
        </Location>

        # Smart Meter Integration SSL settings.
        <Location /sm-integration>
            SSLVerifyClient require
            SSLVerifyDepth 1

            SSLOptions +ExportCertData
        </Location>
        <Location /sm-integration/wsdl>
            SSLVerifyClient none
        </Location>
      </VirtualHost>
    </IfModule>
