apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-config
data:
  httpd.conf: |
{{ .Files.Get "config/httpd/httpd.conf" | indent 4 }}
  vhosts.conf: |
{{ .Files.Get "config/httpd/vhosts.conf" | indent 4 }}
