apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: apache/apache-artemis
          imagePullPolicy: IfNotPresent
          ports:
            - name: apache
              containerPort: 61617
            - name: console
              containerPort: 8161
          env:
            - name: ACTIVEMQ_JMS_SERVER_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apache-jms-server-certs
                  key: keyStorePassword
            - name: ACTIVEMQ_JMS_SERVER_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apache-jms-server-certs
                  key: trustStorePassword
          volumeMounts:
            - name: apache-secrets
              mountPath: /var/lib/artemis-instance/ssl/
            - name: apache-config
              mountPath: /var/lib/artemis-instance/etc-override/
            - name: report-volume
              mountPath: /target/output
      volumes:
        - name: apache-secrets
          secret:
            secretName: apache-jms-server-certs
        - name: apache-config
          configMap:
            name: apache-config
        - name: report-volume
          persistentVolumeClaim:
            claimName: report-volume