apiVersion: v1
kind: ConfigMap
metadata:
  name: gxf-platform-config
data:
  external-interface.properties: |
    flyway.enabled=true
    db.host=postgresql
    db.name=he_external_interface
    db.max_pool_size=20

    db.host.quartz=postgresql-quartz-db-pooler
    db.name.quartz=quartz

  osgp-throttling-service.properties: |
    spring.datasource.url=jdbc:postgresql://postgres:5432/osgp_throttling

      scheduling.task.reinitialize.state.cron.expression=2 0/5 * * * ?
      cleanup.permits.time-to-live=PT5M

  jasper-interface.properties: |-
    # Database host for sending sms wakeup notifications to listening protocol adapters
    db.host=osgp-postgres


  osgp-adapter-protocol-dlms.properties: |-
    db.host.dlms=postgres
    db.max_pool_size=50

  global.properties: |
    # Metrics
    # metrics.prometheus.enabled=true
    # metrics.prometheus.port=9404
    # metrics.prometheus.path=/metrics

    # Postgres
    db.host=postgres
    db.host.domain_logging=postgres
    db.host.core=postgres
    db.host.dlms=postgres
    db.host.oslp=postgres
    db.host.iec61850=postgres
    db.api.host.iec61850=postgres
    db.api.host.oslp=postgres

    # Activemq settings
    jms.default.broker.url=failover:(ssl://activemq:61617)
    jms.default.broker.username=artemis
    jms.default.broker.client.key.store=/etc/ssl/certs/jms/gxf-platform/client.ks
    jms.default.broker.client.key.store.pwd=${ACTIVEMQ_JMS_CLIENT_KEYSTORE_PASSWORD}
    jms.default.broker.client.trust.store=/etc/ssl/certs/jms/gxf-platform/broker.ts
    jms.default.broker.client.trust.store.pwd=${ACTIVEMQ_JMS_CLIENT_TRUSTSTORE_PASSWORD}
    jms.domain.default.broker.url=failover:(ssl://activemq:61617)
    jms.domain.default.broker.username=artemis
    jms.domain.default.broker.client.key.store=/etc/ssl/certs/jms/gxf-platform/client.ks
    jms.domain.default.broker.client.key.store.pwd=${ACTIVEMQ_JMS_CLIENT_KEYSTORE_PASSWORD}
    jms.domain.default.broker.client.trust.store=/etc/ssl/certs/jms/gxf-platform/broker.ts
    jms.domain.default.broker.client.trust.store.pwd=${ACTIVEMQ_JMS_CLIENT_TRUSTSTORE_PASSWORD}
    jms.protocol.default.broker.url=failover:(ssl://activemq:61617)
    jms.protocol.default.broker.username=artemis
    jms.protocol.default.broker.client.key.store=/etc/ssl/certs/jms/gxf-platform/client.ks
    jms.protocol.default.broker.client.key.store.pwd=${ACTIVEMQ_JMS_CLIENT_KEYSTORE_PASSWORD}
    jms.protocol.default.broker.client.trust.store=/etc/ssl/certs/jms/gxf-platform/broker.ts
    jms.protocol.default.broker.client.trust.store.pwd=${ACTIVEMQ_JMS_CLIENT_TRUSTSTORE_PASSWORD}

    # OSLP
    signing.server.security.signkey.path=/etc/ssl/certs/oslp/oslp_test_ecdsa_private.der
    test.device.ips={'TEST1024010101010':'osgp-cucumber-tests-platform-publiclighting'}


  server.xml: |
{{ .Files.Get "config/tomcat/server.xml" | indent 4 }}
