apiVersion: v1
kind: ConfigMap
metadata:
  name: gxf-platform-config
data:
  global.properties: |
    db.host=postgres
    db.port=5432
    db.username=osp_admin
    db.password=1234
    jms.domain.default.broker.url=failover:(tcp://activemq:61616)