kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: report-volume
  labels:
    app: report-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: 'local-storage'
