{{- range $container := .Values.platform.containers -}}
{{- $name := $container.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-sa
  namespace: {{ $.Release.Namespace }}
  labels:
    app: "{{ $name }}"
---
{{- end }}
