{{- range $container := .Values.containers -}}
{{- $name := $container.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ajp
      port: 8009
      targetPort: ajp
    {{- range $extraPort := $container.extraPorts }}
    - name: {{ $extraPort.name }}
      port: {{ $extraPort.port }}
      targetPort: {{ $extraPort.port }}
    {{- end }}
  selector:
    app: {{ $name }}
---
{{- end -}}
