apiVersion: v1
kind: ServiceAccount
metadata:
  name: initcontainer-admin-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: initcontainer-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: initcontainer-admin-sa
    namespace: default
