# Empty, needed for chart testing
config:
  global.properties: |
    # Metrics
    metrics.prometheus.enabled=true
    metrics.prometheus.port=9404
    metrics.prometheus.path=/metrics

    # Postgres
    db.host=postgres
    db.host.domain_logging=postgres
    db.host.core=postgres
    db.host.dlms=postgres
    db.host.oslp=postgres
    db.host.iec61850=postgres
    db.api.host.iec61850=postgres
    db.api.host.oslp=postgres

    # Activemq settings
    jms.default.broker.url=failover:(ssl://activemq:61617)
    jms.default.broker.username=artemis
    jms.default.broker.client.key.store=/etc/ssl/certs/jms/gxf-platform/client.ks
    jms.default.broker.client.key.store.pwd=${ACTIVEMQ_JMS_CLIENT_KEYSTORE_PASSWORD}
    jms.default.broker.client.trust.store=/etc/ssl/certs/jms/gxf-platform/broker.ts
    jms.default.broker.client.trust.store.pwd=${ACTIVEMQ_JMS_CLIENT_TRUSTSTORE_PASSWORD}
    jms.domain.default.broker.url=failover:(ssl://activemq:61617)
    jms.domain.default.broker.username=artemis
    jms.domain.default.broker.client.key.store=/etc/ssl/certs/jms/gxf-platform/client.ks
    jms.domain.default.broker.client.key.store.pwd=${ACTIVEMQ_JMS_CLIENT_KEYSTORE_PASSWORD}
    jms.domain.default.broker.client.trust.store=/etc/ssl/certs/jms/gxf-platform/broker.ts
    jms.domain.default.broker.client.trust.store.pwd=${ACTIVEMQ_JMS_CLIENT_TRUSTSTORE_PASSWORD}
    jms.protocol.default.broker.url=failover:(ssl://activemq:61617)
    jms.protocol.default.broker.username=artemis
    jms.protocol.default.broker.client.key.store=/etc/ssl/certs/jms/gxf-platform/client.ks
    jms.protocol.default.broker.client.key.store.pwd=${ACTIVEMQ_JMS_CLIENT_KEYSTORE_PASSWORD}
    jms.protocol.default.broker.client.trust.store=/etc/ssl/certs/jms/gxf-platform/broker.ts
    jms.protocol.default.broker.client.trust.store.pwd=${ACTIVEMQ_JMS_CLIENT_TRUSTSTORE_PASSWORD}

    # OSLP
    signing.server.security.signkey.path=/etc/ssl/certs/oslp/oslp_test_ecdsa_private.der
    test.device.ips={'TEST1024010101010':'osgp-cucumber-tests-platform-publiclighting'}

    # REDIS
    redis.host=redis

  osgp-throttling-service.properties: |
    spring.datasource.url=jdbc:postgresql://postgres:5432/osgp_throttling

containers:
  - name: osgp-core
    memory: 768Mi
    dependsOn:
      - osgp-logging
  - name: osgp-logging
    memory: 768Mi
  - name: osgp-adapter-domain-admin
    memory: 768Mi
    dependsOn:
      - osgp-core
  - name: osgp-adapter-domain-core
    memory: 768Mi
    dependsOn:
      - osgp-core
  - name: osgp-adapter-domain-tariffswitching
    memory: 768Mi
  - name: osgp-adapter-ws-admin
    memory: 768Mi
    dependsOn:
      - osgp-core
  - name: osgp-adapter-ws-core
    memory: 768Mi
    dependsOn:
      - osgp-core
  - name: osgp-adapter-ws-tariffswitching
    memory: 768Mi
    dependsOn:
      - osgp-core
  - name: osgp-protocol-adapter-iec60870
    memory: 768Mi
  - name: osgp-protocol-adapter-iec61850
    memory: 768Mi
    dependsOn:
      - osgp-core
  - name: osgp-protocol-adapter-oslp
    memory: 768Mi
    extraPorts:
      - name: oslp
        port: 12122
  - name: osgp-signing-server
    memory: 768Mi