apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgweb
  name: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - image: sosedoff/pgweb
          name: pgweb
          env:
            - name: PGWEB_SESSIONS
              value: "true"
            - name: PGWEB_DATABASE_URL
              value: postgres://postgres:psql123!@postgres:5432/postgres?sslmode=disable
            - name: DATABASE_URL
              value: postgres://postgres:psql123!@postgres:5432/postgres?sslmode=disable
          ports:
            - containerPort: 8081
