apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgweb
  name: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      serviceAccountName: initcontainer-admin-sa
      initContainers:
        - name: wait-for-dependencies
          image: bitnami/kubectl:latest
          command:
            - kubectl
            - rollout
            - status
            - deployment
            - postgres
      containers:
        - image: sosedoff/pgweb
          name: pgweb
          env:
            - name: PGWEB_DATABASE_URL
              value: postgres://postgres:psql123!@postgres:5432/postgres?sslmode=disable
          ports:
            - containerPort: 8081
