name: Chart testing
on:
  pull_request:
    branches:
      - main

jobs:
  chart-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Run chart-testing (lint)
        run: ct lint --target-branch feature/FDP-3056-smhe-cucumber-containers

